export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_CURRENCY_HIST_DATA = 'FETCH_CURRENCY_HIST_DATA';
export const FETCH_MUTUAL_FUNDS = 'FETCH_MUTUAL_FUNDS';
export const FETCH_STOCK_LIST = 'FETCH_STOCK_LIST';
export const FETCH_STOCK_HISTORY = 'FETCH_STOCK_HISTORY';
export const FETCH_STOCK_INTRADAY = 'FETCH_STOCK_INTRADAY';
export const FETCH_SECTOR_DATA = 'FETCH_SECTOR_DATA';
export const FETCH_NEWS_FEED = 'FETCH_NEWS_FEED';