export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_CURRENCY_HIST_DATA = 'FETCH_CURRENCY_HIST_DATA';
export const FETCH_MUTUAL_FUNDS = 'FETCH_MUTUAL_FUNDS';
export const FETCH_STOCK_LIST = 'FETCH_STOCK_LIST';